name: Deploy

on:
  push:
    branches: 
      - master
    paths:
      - 'fminfosec.club/**'

jobs:
  sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy files to Dreamhost server
        uses: appleboy/scp-action@v0.0.1
        with: 
          host: fminfosec.club
          username: dh_zm85fr
          password: ${{ secrets.DREAMHOST_FTP_PASSWORD }}
          source: "fminfosec.club/**"
          target: "fminfosec.club"