name: Publish to DreamHost

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4

      - name: Send files to Dreamhost webserver    # Publishes the website static code to the webserver
        uses: SamKirkland/web-deploy@v1
        with: 
          target-server: ${{ secrets.DREAMHOST_SERVER }}
          remote-user: ${{ secrets.DREAMHOST_USERNAME }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination-path: ~/fminfosec.club/
