name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: FTP Deploy
      uses: sebastianpopp/ftp-action@v1.1.0
      with:
        host: sftp://fminfosec.club
        user: dh_zm85fr
        password: ${{ secrets.DREAMHOST_FTP_PASSWORD }}
        local_dir: fminfosec.club
        remote_dir: fminfosec.club
